name: OfflineInvsee
version: 1.0
main: com.zwebfek.invlet.OfflineInvsee
author: zwebfek

commands:
  offlineinvsee:
    usage: /<command> <player>
    description: See a player's inventory when he/she is offline
    permission: OfflineInvsee.basic
    permission-message: You don't have <permission>
permissions:
  OfflineInvsee.basic:
    description: Allow use of the commands in the plugin
    default: op